name = "PBCCompiler"
uuid = "66660b70-1c9c-4e13-82cc-f550c154eed2"
version = "0.1.0"
authors = [
    "Oliver Gao <yuhgao@umass.edu>",
    "Stefan Krastanov <stefan@krastanov.org>",
    "QuantumSavory.jl community contributors"
]

[workspace]
projects = ["benchmark", "docs"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
PBCCompilerMakieExt = "Makie"

[compat]
Accessors = "0.1.44"
JLD2 = "0.6.4"
Makie = "0.24"
Moshi = "0.3"
QuantumClifford = "0.10, 0.11"
Random = "1.11.0"
StatsBase = "0.34.10"
julia = "1.12"
